/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started',
      label: 'Getting Started',
    },
    {
      type: 'category',
      label: 'Installation',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'installation' },
      items: [
        'installation/licheervnano',
        'installation/maixcam',
        'installation/macos',
        'installation/android',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: false,
      link: { type: 'doc', id: 'configuration/index' },
      items: [
        'configuration/model-list',
        'configuration/security-sandbox',
        'configuration/security-reference',
        'configuration/token_authentication',
        'configuration/heartbeat',
        'configuration/tools',
        'configuration/config-reference',
        'credential-encryption',
        'sensitive-data-filtering',
        'configuration/exec',
        'rate-limiting',
      ],
    },
    {
      type: 'category',
      label: 'Chat Channels',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'channels/index' },
      items: [
        'channels/telegram',
        'channels/discord',
        'channels/slack',
        'channels/qq',
        'channels/dingtalk',
        'channels/wecom',
        'channels/feishu',
        'channels/line',
        'channels/onebot',
        'channels/whatsapp',
        'channels/matrix',
        'channels/maixcam',
        'channels/vk',
        'channels/weixin',
      ],
    },
    {
      type: 'category',
      label: 'Providers',
      collapsible: true,
      collapsed: true,
      link: { type: 'doc', id: 'providers/index' },
      items: [
        'providers/antigravity',
        'providers/antigravity-usage',
        'providers/openai-api',
        'providers/gemini-api',
        'providers/openrouter-api',
        'providers/lmstudio-api',
        'providers/siliconflow-api',
        'providers/qwen-api',
        'providers/volcengine-api',
        'providers/zhipu-api',
        'providers/deepseek-api',
        'providers/moonshot-api',
        'providers/minimax-api',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: true,
      collapsed: true,
      items: [
        'hooks',
        'steering',
        'spawn-tasks',
        'context-compression',
        'cron',
      ],
    },
    {
      type: 'category',
      label: 'Deployment',
      collapsible: true,
      collapsed: true,
      items: [
        'docker',
        'hardware-compatibility',
      ],
    },
    {
      type: 'doc',
      id: 'troubleshooting',
      label: 'Troubleshooting',
    },
    {
      type: 'category',
      label: 'Migration',
      collapsible: true,
      collapsed: true,
      items: ['migration/model-list-migration'],
    },
    {
      type: 'category',
      label: 'Development',
      collapsible: true,
      collapsed: true,
      items: [
        'design/provider-refactoring',
        'contributing',
        'roadmap',
      ],
    },
    {
      type: 'doc',
      id: 'changelog',
      label: 'Changelog',
    },
  ],
};

module.exports = sidebars;
